### ISSUE TITLE
App-Header

### ISSUE THREAD

**Issue by thomasweigert91** [thomasweigert91/capstone_project#2]
### Value Proposition

As a user, i want to see in the header which page i am on and have options for further navigation. Various options and features should make the handling easier for me.

### Description

![image](https://user-images.githubusercontent.com/114309234/204253337-89488695-91f7-452a-8ab5-a1a16fd88d64.png)
![image](https://user-images.githubusercontent.com/114309234/204253422-d79c9d20-b3c9-443c-8574-07468c660859.png)
![image](https://user-images.githubusercontent.com/114309234/204259942-1aee66cf-8a5b-4cc9-bc6f-a79373a54238.png)

### Acceptance Criteria

- [ ] the app header is always shown at the top of the app
- [ ] it always contains the name of the current site
- [ ] in addition, in some cases, the user gets individual icons for other features, such as a stopwatch, the possibility to navigate back to the home-screen or save an individual session-plan

### Tasks

- [ ] create a fixed header
- [ ] it always contains the current page name
- [ ] add button, to move back to the home screen from different pages, which do not show the navigation-bar
- [ ] add an option-menu on the profile page
- [ ] add a stop watch feature while in training

### Sizing/Complexity

**M**
