### ISSUE TITLE
Home-Page

### ISSUE THREAD

**Issue by thomasweigert91** [thomasweigert91/capstone_project#3]
### Value Proposition

As a user, I would like to see important information about my past workouts on the home page to get more overview of my progress and achievements at a glance.

### Description

![image](https://user-images.githubusercontent.com/114309234/204267778-09b36078-9c17-45ae-84cc-1bda207ec377.png)

### Acceptance Criteria

- [ ] the home-page opens on every start
- [ ] show cards, which contain some informations about the recent workouts
- [ ] possibility to

### Tasks

(for developers team)

- [ ] render the latest workouts in cards
- [ ] possibility to click on the cards to
- [ ] possibility to get to the corresponding workout by clicking on the card

### Sizing/Complexity

**M**

**Comment by WilhelmAlfke** [comment]
hi @thomasweigert91 , nice user story and especially a beautiful wireframe. 
here's some suggestions: landing page ("home") is where you usually end up when opening the app, so you don't really need the first criteria. instead of "show cards, which.." rather try a more clear syntax like: 
- [ ] the landing page shows cards
- [ ] the cards contain information about the last checkout
  

ps: the task section is for developers only anyway, so no need to mention it. 🦊 
thats why you might want to be more clear here what you as the developer has to do, e.g. 
- [ ] write a function that <describe function> 
- [ ] create a button to show corresponding workout
